In [1]:
import requests
import pandas as pd
import json
import numpy as np

# Get Weather Data

Geo coords for Dhaka, Chittagong, and Patuakhali

In [2]:
# tuple as (lat, lon)
dhk_coords = (23.7104, 90.40744)
cht_coords = (22.3384, 91.83168)
pat_coords = (22.36833, 90.3458)

In [6]:
def get_city_weather(coords):
    weather_api_url = f"https://api.open-meteo.com/v1/forecast?latitude={coords[0]}&longitude={coords[1]}&daily=relative_humidity_2m_mean,temperature_2m_max,temperature_2m_min,temperature_2m_mean,rain_sum,sunshine_duration&forecast_days=7&timezone=Asia/Dhaka"
    response = requests.get(weather_api_url)

    try:
        response.raise_for_status()
        data = response.json()

        return data
    except requests.exceptions.RequestException as e:
        print(e)

In [7]:
dhaka_data = get_city_weather(dhk_coords)
dhaka_data

{'latitude': 23.75,
 'longitude': 90.375,
 'generationtime_ms': 0.11456012725830078,
 'utc_offset_seconds': 21600,
 'timezone': 'Asia/Dhaka',
 'timezone_abbreviation': 'GMT+6',
 'elevation': 27.0,
 'daily_units': {'time': 'iso8601',
  'relative_humidity_2m_mean': '%',
  'temperature_2m_max': '°C',
  'temperature_2m_min': '°C',
  'temperature_2m_mean': '°C',
  'rain_sum': 'mm',
  'sunshine_duration': 's'},
 'daily': {'time': ['2025-10-04',
   '2025-10-05',
   '2025-10-06',
   '2025-10-07',
   '2025-10-08',
   '2025-10-09',
   '2025-10-10'],
  'relative_humidity_2m_mean': [87, 89, 90, 90, 90, 93, 94],
  'temperature_2m_max': [31.8, 30.6, 30.2, 29.9, 28.8, 27.2, 25.7],
  'temperature_2m_min': [26.0, 25.7, 25.2, 25.0, 24.9, 24.7, 24.7],
  'temperature_2m_mean': [28.2, 27.4, 26.8, 26.9, 26.4, 25.6, 25.0],
  'rain_sum': [0.0, 0.0, 0.0, 0.0, 0.0, 0.7, 0.2],
  'sunshine_duration': [32260.79,
   19657.66,
   18125.03,
   19881.97,
   17205.59,
   0.0,
   0.0]}}

In [8]:
city_weather_df = pd.DataFrame(
    columns=[
        "Date",  # Remove Date before passed to model
        "Rainfall",
        "Sunshine",
        "Humidity",
        "Temp_mean",
        "Temp_max",
        "Temp_min",
        "Year",
        "Month",
        "loadshed_prev",
        "generation_prev",
    ]
)
city_weather_df

Empty DataFrame
Columns: [Date, Rainfall, Sunshine, Humidity, Temp_mean, Temp_max, Temp_min, Year, Month, loadshed_prev, generation_prev]
Index: []

In [9]:
dhaka_data["daily"]

{'time': ['2025-10-04',
  '2025-10-05',
  '2025-10-06',
  '2025-10-07',
  '2025-10-08',
  '2025-10-09',
  '2025-10-10'],
 'relative_humidity_2m_mean': [87, 89, 90, 90, 90, 93, 94],
 'temperature_2m_max': [31.8, 30.6, 30.2, 29.9, 28.8, 27.2, 25.7],
 'temperature_2m_min': [26.0, 25.7, 25.2, 25.0, 24.9, 24.7, 24.7],
 'temperature_2m_mean': [28.2, 27.4, 26.8, 26.9, 26.4, 25.6, 25.0],
 'rain_sum': [0.0, 0.0, 0.0, 0.0, 0.0, 0.7, 0.2],
 'sunshine_duration': [32260.79,
  19657.66,
  18125.03,
  19881.97,
  17205.59,
  0.0,
  0.0]}

In [10]:
daily_data = dhaka_data["daily"]

city_weather_df["Date"] = daily_data["time"]
city_weather_df["Date"] = pd.to_datetime(city_weather_df["Date"], format="%Y-%m-%d")
city_weather_df["Year"] = city_weather_df["Date"].dt.year
city_weather_df["Month"] = city_weather_df["Date"].dt.month

city_weather_df["Rainfall"] = daily_data["rain_sum"]
city_weather_df["Sunshine"] = daily_data["sunshine_duration"]
city_weather_df["Sunshine"] = city_weather_df["Sunshine"] / (60 * 60)
city_weather_df["Humidity"] = daily_data["relative_humidity_2m_mean"]

city_weather_df["Temp_mean"] = daily_data["temperature_2m_mean"]
city_weather_df["Temp_max"] = daily_data["temperature_2m_max"]
city_weather_df["Temp_min"] = daily_data["temperature_2m_min"]

city_weather_df

,Date,Rainfall,Sunshine,Humidity,Temp_mean,Temp_max,Temp_min,Year,Month,loadshed_prev,generation_prev
0,2025-10-04,0.0,8.961331,87,28.2,31.8,26.0,2025,10,NaN,NaN
1,2025-10-05,0.0,5.460461,89,27.4,30.6,25.7,2025,10,NaN,NaN
2,2025-10-06,0.0,5.034731,90,26.8,30.2,25.2,2025,10,NaN,NaN
3,2025-10-07,0.0,5.522769,90,26.9,29.9,25.0,2025,10,NaN,NaN
4,2025-10-08,0.0,4.779331,90,26.4,28.8,24.9,2025,10,NaN,NaN
5,2025-10-09,0.7,0.000000,93,25.6,27.2,24.7,2025,10,NaN,NaN
6,2025-10-10,0.2,0.000000,94,25.0,25.7,24.7,2025,10,NaN,NaN

In [11]:
def get_city_weather_df(daily_data):
    city_df = pd.DataFrame(
        columns=[
            "Date",  # Remove Date before passed to model
            "Rainfall",
            "Sunshine",
            "Humidity",
            "Temp_mean",
            "Temp_max",
            "Temp_min",
            "Year",
            "Month",
            "loadshed_prev",
            "generation_prev",
        ]
    )

    city_df["Date"] = daily_data["time"]
    city_df["Date"] = pd.to_datetime(city_df["Date"], format="%Y-%m-%d")
    city_df["Year"] = city_df["Date"].dt.year
    city_df["Month"] = city_df["Date"].dt.month

    city_df["Rainfall"] = daily_data["rain_sum"]
    city_df["Sunshine"] = daily_data["sunshine_duration"]
    # Convert seconds to hours
    city_df["Sunshine"] = city_df["Sunshine"] / (60 * 60)
    city_df["Humidity"] = daily_data["relative_humidity_2m_mean"]

    city_df["Temp_mean"] = daily_data["temperature_2m_mean"]
    city_df["Temp_max"] = daily_data["temperature_2m_max"]
    city_df["Temp_min"] = daily_data["temperature_2m_min"]

    return city_df

## Get weather data of all locations

In [12]:
dhk_data = get_city_weather(dhk_coords)
dhk_weather_df = get_city_weather_df(dhk_data["daily"])
dhk_weather_df

,Date,Rainfall,Sunshine,Humidity,Temp_mean,Temp_max,Temp_min,Year,Month,loadshed_prev,generation_prev
0,2025-10-04,0.0,8.961331,87,28.2,31.8,26.0,2025,10,NaN,NaN
1,2025-10-05,0.0,5.460461,89,27.4,30.6,25.7,2025,10,NaN,NaN
2,2025-10-06,0.0,5.034731,90,26.8,30.2,25.2,2025,10,NaN,NaN
3,2025-10-07,0.0,5.522769,90,26.9,29.9,25.0,2025,10,NaN,NaN
4,2025-10-08,0.0,4.779331,90,26.4,28.8,24.9,2025,10,NaN,NaN
5,2025-10-09,0.7,0.000000,93,25.6,27.2,24.7,2025,10,NaN,NaN
6,2025-10-10,0.2,0.000000,94,25.0,25.7,24.7,2025,10,NaN,NaN

In [13]:
cht_data = get_city_weather(cht_coords)
cht_weather_df = get_city_weather_df(cht_data["daily"])
cht_weather_df

,Date,Rainfall,Sunshine,Humidity,Temp_mean,Temp_max,Temp_min,Year,Month,loadshed_prev,generation_prev
0,2025-10-04,0.0,10.804842,83,28.5,29.5,27.3,2025,10,NaN,NaN
1,2025-10-05,0.0,9.622086,85,28.1,28.9,27.3,2025,10,NaN,NaN
2,2025-10-06,0.0,6.983547,87,27.8,28.4,27.2,2025,10,NaN,NaN
3,2025-10-07,0.0,8.008364,86,27.5,28.4,26.9,2025,10,NaN,NaN
4,2025-10-08,0.0,4.634292,86,27.6,28.4,26.9,2025,10,NaN,NaN
5,2025-10-09,0.0,2.713022,84,27.8,28.6,27.1,2025,10,NaN,NaN
6,2025-10-10,2.1,0.000000,88,27.1,27.5,26.7,2025,10,NaN,NaN

In [14]:
pat_data = get_city_weather(pat_coords)
pat_weather_df = get_city_weather_df(pat_data["daily"])
pat_weather_df

,Date,Rainfall,Sunshine,Humidity,Temp_mean,Temp_max,Temp_min,Year,Month,loadshed_prev,generation_prev
0,2025-10-04,0.0,10.429186,87,28.4,31.1,26.6,2025,10,NaN,NaN
1,2025-10-05,0.0,4.076286,89,27.8,29.7,26.4,2025,10,NaN,NaN
2,2025-10-06,0.0,6.547400,89,27.5,30.5,25.8,2025,10,NaN,NaN
3,2025-10-07,0.0,7.203269,90,27.2,29.6,25.7,2025,10,NaN,NaN
4,2025-10-08,0.0,2.234150,90,26.8,29.2,25.6,2025,10,NaN,NaN
5,2025-10-09,0.0,0.000000,93,26.2,27.3,25.4,2025,10,NaN,NaN
6,2025-10-10,0.0,0.000000,93,26.0,27.9,24.9,2025,10,NaN,NaN

In [15]:
all_weather_df = pd.concat([dhk_weather_df, cht_weather_df, pat_weather_df])

all_weather_df = (
    all_weather_df.groupby("Date")
    .agg(
        {
            "Rainfall": "mean",
            "Sunshine": "mean",
            "Humidity": "mean",
            "Temp_mean": "mean",
            "Temp_max": "max",
            "Temp_min": "min",
            "Year": "first",
            "Month": "first",
            "loadshed_prev": "first",
            "generation_prev": "first",
        }
    )
    .reset_index()
)

all_weather_df

,Date,Rainfall,Sunshine,Humidity,Temp_mean,Temp_max,Temp_min,Year,Month,loadshed_prev,generation_prev
0,2025-10-04,0.000000,10.065119,85.666667,28.366667,31.8,26.0,2025,10,None,None
1,2025-10-05,0.000000,6.386278,87.666667,27.766667,30.6,25.7,2025,10,None,None
2,2025-10-06,0.000000,6.188559,88.666667,27.366667,30.5,25.2,2025,10,None,None
3,2025-10-07,0.000000,6.911468,88.666667,27.200000,29.9,25.0,2025,10,None,None
4,2025-10-08,0.000000,3.882591,88.666667,26.933333,29.2,24.9,2025,10,None,None
5,2025-10-09,0.233333,0.904341,90.000000,26.533333,28.6,24.7,2025,10,None,None
6,2025-10-10,0.766667,0.000000,91.666667,26.033333,27.9,24.7,2025,10,None,None

# Get Previous Day's Electricity Data

In [16]:
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

yesterday_date = datetime.now(ZoneInfo("Asia/Dhaka")) - timedelta(days=1)

yesterday_date = yesterday_date.strftime("%d-%m-%Y")
yesterday_date

'03-10-2025'

In [ ]:
import io

pgcb_url = (
    f"https://erp.powergrid.gov.bd/web/generations/view_demand_supply_loadshed?page=1"
)

try:
    pgcb_res = requests.get(pgcb_url, verify=False)
    pgcb_res.raise_for_status()
    html = pgcb_res.text

    tables = pd.read_html(io.StringIO(html))

    electricity_df = tables[0]

    # electricity_df.columns = electricity_df.columns.droplevel(0)
    electricity_df = electricity_df[
        ["Date", "Demand (MW)", "Demand(MW)", "Loadshed"]
    ].copy()

    electricity_df = electricity_df[electricity_df["Date"] == yesterday_date]

    electricity_df.rename(
        columns={
            "Demand (MW)": "Generation",
            "Demand(MW)": "Demand",
        },
        inplace=True,
    )

    # Convert units from MW to GW
    electricity_df[["Generation", "Demand", "Loadshed"]] = (
        electricity_df[["Generation", "Demand", "Loadshed"]] / 1000
    )
except requests.exceptions.RequestException as e:
    print(e)

/home/mashrur/anaconda3/envs/my_env/lib/python3.12/site-packages/urllib3/connectionpool.py:2303: InsecureRequestWarning: Unverified HTTPS request is being made to host 'erp.pgcb.gov.bd'. Adding certificate verification is strongly advised. See: https://urllib3future.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [18]:
electricity_df

          Date  Generation  Demand  Loadshed
10  03-10-2025      12.949  12.949       0.0
11  03-10-2025      13.038  13.038       0.0
12  03-10-2025      12.946  12.946       0.0
13  03-10-2025      12.866  12.866       0.0
14  03-10-2025      12.749  12.749       0.0
15  03-10-2025      12.720  12.720       0.0
16  03-10-2025      12.658  12.658       0.0
17  03-10-2025      11.654  11.654       0.0
18  03-10-2025      10.233  10.233       0.0
19  03-10-2025      10.082  10.082       0.0
20  03-10-2025      10.572  10.572       0.0
21  03-10-2025      11.062  11.062       0.0
22  03-10-2025      11.685  11.685       0.0
23  03-10-2025      10.822  10.822       0.0
24  03-10-2025       9.995   9.995       0.0
25  03-10-2025       9.880   9.880       0.0
26  03-10-2025       9.829   9.829       0.0
27  03-10-2025      10.021  10.021       0.0
28  03-10-2025      10.168  10.168       0.0
29  03-10-2025      10.451  10.451       0.0
30  03-10-2025      10.981  10.981       0.0
31  03-10-2025      11.240  11.240       0.0
32  03-10-2025      11.589  11.589       0.0
33  03-10-2025      11.936  11.936       0.0
34  03-10-2025      12.377  12.377       0.0

In [19]:
input_df = all_weather_df.copy()

# input_df.loc[0, "generation_prev"] = electricity_df["Generation"].sum()
# input_df.loc[0, "loadshed_prev"] = electricity_df["Loadshed"].sum()
input_df

,Date,Rainfall,Sunshine,Humidity,Temp_mean,Temp_max,Temp_min,Year,Month,loadshed_prev,generation_prev
0,2025-10-04,0.000000,10.065119,85.666667,28.366667,31.8,26.0,2025,10,None,None
1,2025-10-05,0.000000,6.386278,87.666667,27.766667,30.6,25.7,2025,10,None,None
2,2025-10-06,0.000000,6.188559,88.666667,27.366667,30.5,25.2,2025,10,None,None
3,2025-10-07,0.000000,6.911468,88.666667,27.200000,29.9,25.0,2025,10,None,None
4,2025-10-08,0.000000,3.882591,88.666667,26.933333,29.2,24.9,2025,10,None,None
5,2025-10-09,0.233333,0.904341,90.000000,26.533333,28.6,24.7,2025,10,None,None
6,2025-10-10,0.766667,0.000000,91.666667,26.033333,27.9,24.7,2025,10,None,None

In [20]:
input_df.dtypes

Date               datetime64[ns]
Rainfall                  float64
Sunshine                  float64
Humidity                  float64
Temp_mean                 float64
Temp_max                  float64
Temp_min                  float64
Year                        int32
Month                       int32
loadshed_prev              object
generation_prev            object
dtype: object

# Load Model

In [21]:
import lightgbm as lgb

generation_model = lgb.Booster(model_file="models/generation_lgbm_model.txt")
loadshed_model = lgb.Booster(model_file="models/loadshed_lgbm_model.txt")

In [22]:
# Set initial values
generation_previous = electricity_df["Generation"].sum()
loadshed_previous = electricity_df["Loadshed"].sum()

forecasts = []

for idx in range(len(input_df)):
    row = input_df.iloc[idx].to_frame().T.infer_objects()

    row["generation_prev"] = generation_previous
    row["loadshed_prev"] = loadshed_previous

    generation_pred = generation_model.predict(row.drop(columns="Date"))[0]
    generation_previous = generation_pred

    loadshed_pred = loadshed_model.predict(row.drop(columns="Date"))[0]
    loadshed_previous = loadshed_pred

    daily_forecast = {
        "date": row["Date"].astype(str).values[0],
        "prediction": {
            "generation": generation_pred,
            "loadshed": loadshed_pred,
        },
    }
    forecasts.append(daily_forecast)

In [23]:
forecasts

[{'date': '2025-10-04',
  'prediction': {'generation': 297.01504296902624,
   'loadshed': 0.4312695361228198}},
 {'date': '2025-10-05',
  'prediction': {'generation': 315.51922533569024,
   'loadshed': 0.6513803934535874}},
 {'date': '2025-10-06',
  'prediction': {'generation': 311.3636254820189,
   'loadshed': 0.458977444985676}},
 {'date': '2025-10-07',
  'prediction': {'generation': 298.4408734581065,
   'loadshed': 0.25916354160366456}},
 {'date': '2025-10-08',
  'prediction': {'generation': 304.11744361423973,
   'loadshed': 0.5175795851297789}},
 {'date': '2025-10-09',
  'prediction': {'generation': 308.32688197493985,
   'loadshed': 0.5479076123198999}},
 {'date': '2025-10-10',
  'prediction': {'generation': 298.2136022135375,
   'loadshed': 0.6792677310361289}}]